name: FirstFlow
on: push
   
jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pip 
        uses: actions/cache@v4
        with: 
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**requirements.txt') }}
            restore-keys:
                ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  lint:
    runs-on: ubuntu-latest
    container: python:3.12

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Cache pip 
          uses: actions/cache@v4
          with: 
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**requirements.txt') }}
              restore-keys:
                  ${{ runner.os }}-pip-

        - name: Install black
          run: pip install black
          
        - name: Run black lint
          run: black --check .