name: FirstFlow
on: push
   
jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest